language: python

dist: xenial

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - cmake
      - git

env:
  - NJOY=${TRAVIS_BUILD_DIR}/NJOY2016/build/njoy

python:
  - "3.6"

branches:
  except: gh-pages

before_install:
  - git clone https://github.com/njoy/NJOY2016.git && (cd NJOY2016 && mkdir build && cd build && cmake .. && make) # install NJOY
  - rm -rf NJOY2016/tests
  - pip install sphinx sphinx_rtd_theme codecov numpydoc

install:
  - python setup.py install

script:
  - pytest
#  - (git clone https://gist.github.com/luca-fiorito-11/ad352e80b01f81fe12599c079f7cb9d7 && cd ad352e80b01f81fe12599c079f7cb9d7 && python  sandy_get_eigenvalues.py ../sandy/data/U5/u235.endf)

after_success:
  - codecov --file coverage/lcov.info --disable search

# Set up sphinx configuration file and produce SANDY documentation in html.
before_deploy:
  - bash make_docs.sh html

# Deploy SANDY docs to gihub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "api_docs/build/html"
  keep-history: false
  overwrite: true
  on:
    branch: master
