language: python

addons:
  apt:
    packages:
      - gfortran

python:
  - "3.6"

branches:
  except: gh-pages

before_install:
  - pip install sphinx sphinx_rtd_theme codecov numpydoc

install:
  - python setup.py install

script:
  - pytest
  - (git clone https://gist.github.com/luca-fiorito-11/ad352e80b01f81fe12599c079f7cb9d7 && cd ad352e80b01f81fe12599c079f7cb9d7 && python  sandy_get_eigenvalues.py ../sandy/data/U5/u235.endf)

after_success:
  - codecov --file coverage/lcov.info --disable search

# Set up sphinx configuration file and produce SANDY documentation in html.
before_deploy:
  - sphinx-quickstart --sep --dot _ --language en --suffix .rst --master index --makefile --batchfile --use-make-mode --author "Luca Fiorito" --project "SANDY API" -v 1 --release 0 --ext-autodoc --ext-doctest --ext-githubpages --ext-mathjax --extensions numpydoc api_docs
  - sed -i '13i\   sandy' api_docs/source/index.rst 
  - sed -i "s/alabaster/sphinx_rtd_theme/" api_docs/source/conf.py
  - sphinx-apidoc --separate --force --module-first -o api_docs/source sandy >/dev/null 2>&1
  - cd api_docs && make html

# Deploy SANDY docs to gihub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "html/_build/html"
  keep-history: false
  overwrite: true
  on:
    branch: master
