name: API docs deployment

on:
  push:
    branches:
      - develop

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: make docs
        run: bash make_docs.sh html
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: api_docs/
          destination-github-username: 'luca-fiorito-11'
          destination-repository-name: 'sandy_notebooks'
          user-email: lucafiorito.11@gmail.com
          commit-message: pushing api docs...
          target-branch: api_docs
